[now]
url=/usr/share/yearn/songs/pagibig.mp3
lyrics=/usr/share/yearn/pagibig.txt
artist=fitterkarma
title=Pag-Ibig ay Kanibalismo II
delay=0.8

[demo]
url=https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3
lyrics=/usr/share/yearn/demo.txt
artist=SoundHelix
title=Song 1
delay=1.0

[chill]
url=https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3
lyrics=/usr/share/yearn/chill.txt
artist=SoundHelix
title=Song 2
delay=0.9

[vibe]
url=https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3
lyrics=/usr/share/yearn/vibe.txt
artist=SoundHelix
title=Song 3
delay=0.8
