#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev 2>/dev/null
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /run

export HOME=/root
export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export TERM=linux

exec setsid cttyhack /usr/bin/bash --login
