#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev 2>/dev/null
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /run

hostname yearneros

export HOME=/root
export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export TERM=linux

echo "nameserver 8.8.8.8" > /etc/resolv.conf

if [ -d /sys/class/net/eth0 ]; then
    ifconfig eth0 up 2>/dev/null
    udhcpc -i eth0 -s /usr/share/udhcpc/default.script -q -n 2>/dev/null &
fi

exec setsid cttyhack /usr/bin/bash --login
